const sampleListings = [
  {
    title: "Intern Room Near Electronic City",
    description: "Budget-friendly shared room ideal for tech interns. Fast WiFi and walking distance to IT parks.",
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=60",
    price: 8500,
    location: "Bangalore",
    country: "India",
    wifiSpeed: "120 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "1 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["Infosys", "TCS", "Wipro"],
    internFriendlyRating: 4.5,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "900m",
    availableFrom: new Date("2026-06-01"),
    recommendedFor: ["Engineering Interns", "Software Developers"],
  },

  {
    title: "Private Studio for Corporate Interns",
    description: "Fully furnished private studio perfect for MBA and corporate interns.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 16000,
    location: "Gurgaon",
    country: "India",
    wifiSpeed: "300 Mbps",
    internDuration: "1-6 Months",
    distanceFromTechPark: "400m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Co-Living",
    roomType: "Private",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Deloitte", "Google", "Accenture"],
    internFriendlyRating: 4.8,
    verifiedByPlatform: true,
    workspaceType: "Private Study Room",
    metroDistance: "250m",
    availableFrom: new Date("2026-05-15"),
    recommendedFor: ["MBA Students", "Corporate Interns"],
  },

  {
    title: "Girls PG Near Cyber Hub",
    description: "Safe and secure girls-only accommodation with CCTV and biometric entry.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Delhi",
    country: "India",
    wifiSpeed: "150 Mbps",
    internDuration: "1-4 Months",
    distanceFromTechPark: "1.5 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Girls Only",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["EY", "HCL", "KPMG"],
    internFriendlyRating: 4.6,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "300m",
    availableFrom: new Date("2026-06-10"),
    recommendedFor: ["Finance Interns", "Female Students"],
  },

  {
    title: "Co-Living Intern House",
    description: "Modern co-living space with networking-friendly environment.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 10500,
    location: "Hyderabad",
    country: "India",
    wifiSpeed: "200 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "800m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Microsoft", "Amazon"],
    internFriendlyRating: 4.7,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "1 km",
    availableFrom: new Date("2026-05-25"),
    recommendedFor: ["Engineering Interns", "Startup Interns"],
  },

  {
    title: "Affordable Boys Internship PG",
    description: "Budget boys-only PG near major IT offices with high-speed broadband.",
    image: "https://images.unsplash.com/photo-1617098474202-0d0f60a09e1c?auto=format&fit=crop&w=800&q=60",
    price: 7500,
    location: "Kolkata",
    country: "India",
    wifiSpeed: "100 Mbps",
    internDuration: "1-2 Months",
    distanceFromTechPark: "1.3 km",
    studyDesk: true,
    powerBackup: false,
    cctv: true,
    biometricEntry: false,
    genderType: "Boys Only",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: false,
    nearCompanies: ["TCS", "Cognizant"],
    internFriendlyRating: 4.2,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "700m",
    availableFrom: new Date("2026-06-05"),
    recommendedFor: ["Engineering Students"],
  },

  // 15 more simplified but fully valid entries
  {
    title: "Intern Flat Near Hinjewadi IT Park",
    description: "Shared apartment ideal for short-term tech internships.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Pune",
    country: "India",
    wifiSpeed: "150 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "600m",
    studyDesk: true,
    powerBackup: true,
    cctv: false,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Infosys", "Capgemini"],
    internFriendlyRating: 4.4,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "1.2 km",
    availableFrom: new Date("2026-06-20"),
    recommendedFor: ["Software Interns"],
  },

  {
    title: "Luxury Internship Suite",
    description: "Premium private suite for high-level corporate internships.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=60",
    price: 18000,
    location: "Mumbai",
    country: "India",
    wifiSpeed: "400 Mbps",
    internDuration: "1-6 Months",
    distanceFromTechPark: "300m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Co-Living",
    roomType: "Private",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["JP Morgan", "BCG"],
    internFriendlyRating: 4.9,
    verifiedByPlatform: true,
    workspaceType: "Private Study Room",
    metroDistance: "200m",
    availableFrom: new Date("2026-05-01"),
    recommendedFor: ["MBA Interns", "Finance Interns"],
  },

  {
    title: "Student Hostel Near Tech Corridor",
    description: "Affordable hostel stay perfect for 2-month internships.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
    price: 7000,
    location: "Chennai",
    country: "India",
    wifiSpeed: "80 Mbps",
    internDuration: "1-2 Months",
    distanceFromTechPark: "2 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["Zoho", "Cognizant"],
    internFriendlyRating: 4.1,
    verifiedByPlatform: false,
    workspaceType: "Common Workspace",
    metroDistance: "900m",
    availableFrom: new Date("2026-06-12"),
    recommendedFor: ["First-Time Interns"],
  },

  {
    title: "Noida Intern Co-Living Space",
    description: "Modern co-living setup with fast WiFi and shared workspace.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Noida",
    country: "India",
    wifiSpeed: "200 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "700m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["HCL", "Adobe"],
    internFriendlyRating: 4.6,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "500m",
    availableFrom: new Date("2026-06-08"),
    recommendedFor: ["Tech Interns"],
  },

  {
    title: "Ahmedabad Intern Residency",
    description: "Secure and verified accommodation near major IT hubs.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=60",
    price: 8200,
    location: "Ahmedabad",
    country: "India",
    wifiSpeed: "120 Mbps",
    internDuration: "1-4 Months",
    distanceFromTechPark: "1 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["TCS", "Infosys"],
    internFriendlyRating: 4.3,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "600m",
    availableFrom: new Date("2026-06-18"),
    recommendedFor: ["Engineering Interns"],
  },
  {
  title: "Bangalore TechNest Residency",
  description: "Premium intern-friendly stay near Electronic City tech corridor.",
  image : "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww",
  price: 10500,
  location: "Bangalore",
  country: "India",
  wifiSpeed: "200 Mbps",
  internDuration: "2-6 Months",
  distanceFromTechPark: "800m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Wipro", "HCL"],
  internFriendlyRating: 4.6,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "1 km",
  availableFrom: new Date("2026-07-01"),
  recommendedFor: ["Software Interns"]
},

{
  title: "Hyderabad HITEC Intern House",
  description: "Affordable and secure housing near HITEC City.",
  image:"https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aG90ZWwlMjByb29tfGVufDB8fDB8fHww",
  price: 9000,
  location: "Hyderabad",
  country: "India",
  wifiSpeed: "150 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "1.2 km",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Boys Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["Microsoft", "Amazon"],
  internFriendlyRating: 4.4,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "900m",
  availableFrom: new Date("2026-06-25"),
  recommendedFor: ["AI Interns"]
},

{
  title: "Pune Startup Habitat",
  description: "Modern co-living for startup interns near Hinjewadi.",
  image : "https://images.unsplash.com/photo-1531668720450-39cf1563fab9?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8c3R1ZHklMjByb29tfGVufDB8fDB8fHww",
  price: 7800,
  location: "Pune",
  country: "India",
  wifiSpeed: "100 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "700m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Infosys", "Cognizant"],
  internFriendlyRating: 4.2,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "1.5 km",
  availableFrom: new Date("2026-07-10"),
  recommendedFor: ["Startup Interns"]
},

{
  title: "Chennai OMR Intern Villa",
  description: "Comfortable intern housing near OMR IT corridor.",
  image : "https://images.unsplash.com/photo-1531079997448-485eb7235a2b?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  price: 8500,
  location: "Chennai",
  country: "India",
  wifiSpeed: "130 Mbps",
  internDuration: "2-5 Months",
  distanceFromTechPark: "900m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Girls Only",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Zoho", "TCS"],
  internFriendlyRating: 4.5,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "800m",
  availableFrom: new Date("2026-06-20"),
  recommendedFor: ["Engineering Interns"]
},

{
  title: "Noida Sector 62 Intern Hub",
  description: "Smart accommodation close to major IT offices.",
  image:"https://images.unsplash.com/photo-1611817084000-13da78818a0f?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 9500,
  location: "Noida",
  country: "India",
  wifiSpeed: "180 Mbps",
  internDuration: "1-6 Months",
  distanceFromTechPark: "600m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: false,
  laundry: true,
  nearCompanies: ["HCL", "Paytm"],
  internFriendlyRating: 4.7,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "500m",
  availableFrom: new Date("2026-07-05"),
  recommendedFor: ["Fintech Interns"]
},

{
  title: "Gurgaon Cyber Residency",
  description: "Intern-focused housing near Cyber City.",
  image : "https://images.unsplash.com/photo-1611817084000-13da78818a0f?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 11000,
  location: "Gurgaon",
  country: "India",
  wifiSpeed: "220 Mbps",
  internDuration: "2-6 Months",
  distanceFromTechPark: "500m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Google", "Deloitte"],
  internFriendlyRating: 4.8,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "400m",
  availableFrom: new Date("2026-06-28"),
  recommendedFor: ["Corporate Interns"]
},

{
  title: "Kolkata Sector V Intern Stay",
  description: "Budget-friendly stay near Salt Lake IT hub.",
  image:"https://images.unsplash.com/photo-1555116505-38ab61800975?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 6500,
  location: "Kolkata",
  country: "India",
  wifiSpeed: "100 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "1 km",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["TCS", "Capgemini"],
  internFriendlyRating: 4.1,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "1.2 km",
  availableFrom: new Date("2026-06-22"),
  recommendedFor: ["IT Interns"]
},

// 13 More Below (Compact Variation)

{
  title: "Mumbai Andheri Intern Loft",
  description: "Secure co-living near SEEPZ IT Park.",
  image : "https://images.unsplash.com/photo-1567774040705-e55e313f6079?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 12000,
  location: "Mumbai",
  country: "India",
  wifiSpeed: "250 Mbps",
  internDuration: "2-6 Months",
  distanceFromTechPark: "700m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Accenture", "L&T"],
  internFriendlyRating: 4.9,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "600m",
  availableFrom: new Date("2026-07-15"),
  recommendedFor: ["Tech Interns"]
},

{
  title: "Jaipur Digital Intern Stay",
  description: "Affordable PG near IT parks in Jaipur.",
  image : "https://images.unsplash.com/photo-1547043736-b2247cb34b01?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 6000,
  location: "Jaipur",
  country: "India",
  wifiSpeed: "80 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "1.5 km",
  studyDesk: true,
  powerBackup: false,
  cctv: true,
  biometricEntry: false,
  genderType: "Boys Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["Genpact"],
  internFriendlyRating: 3.9,
  verifiedByPlatform: false,
  workspaceType: "Common Workspace",
  metroDistance: "2 km",
  availableFrom: new Date("2026-06-30"),
  recommendedFor: ["Management Interns"]
},
{
  title: "Indore IT Park Residency",
  description: "Comfortable intern housing near Crystal IT Park.",
  image : "https://plus.unsplash.com/premium_photo-1725408151382-c61346b6a6cd?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzd8fHN0dWR5JTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 7200,
  location: "Indore",
  country: "India",
  wifiSpeed: "120 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "900m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Impinge Solutions", "Yash Technologies"],
  internFriendlyRating: 4.0,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "1.8 km",
  availableFrom: new Date("2026-07-08"),
  recommendedFor: ["IT Interns"]
},

{
  title: "Lucknow Tech Habitat",
  description: "Affordable PG for interns near IT City Lucknow.",
  image : "https://images.unsplash.com/photo-1565629196891-2ddb37c9e9fc?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  price: 6500,
  location: "Lucknow",
  country: "India",
  wifiSpeed: "90 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "1.3 km",
  studyDesk: true,
  powerBackup: false,
  cctv: true,
  biometricEntry: false,
  genderType: "Boys Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["TCS"],
  internFriendlyRating: 3.8,
  verifiedByPlatform: false,
  workspaceType: "Common Workspace",
  metroDistance: "2 km",
  availableFrom: new Date("2026-06-29"),
  recommendedFor: ["Software Interns"]
},

{
  title: "Bhopal Startup Residency",
  description: "Intern-friendly stay near MP Nagar tech offices.",
  image:"https://plus.unsplash.com/premium_photo-1716767947595-da9f70b8da3b?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D",
  price: 6800,
  location: "Bhopal",
  country: "India",
  wifiSpeed: "110 Mbps",
  internDuration: "2-5 Months",
  distanceFromTechPark: "1 km",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Persistent Systems"],
  internFriendlyRating: 4.2,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "1.6 km",
  availableFrom: new Date("2026-07-03"),
  recommendedFor: ["Startup Interns"]
},

{
  title: "Nagpur IT Intern Stay",
  description: "Secure accommodation near MIHAN IT Park.",
  image: "https://images.unsplash.com/photo-1695204905741-9d099a5989ce?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D",
  price: 7000,
  location: "Nagpur",
  country: "India",
  wifiSpeed: "100 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "800m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Girls Only",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Infosys"],
  internFriendlyRating: 4.3,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "1.4 km",
  availableFrom: new Date("2026-07-12"),
  recommendedFor: ["Engineering Interns"]
},

{
  title: "Coimbatore Tech Intern Hub",
  description: "Modern co-living near TIDEL Park Coimbatore.",
  image : "https://images.unsplash.com/photo-1608198399988-341f712c3711?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D",
  price: 7500,
  location: "Coimbatore",
  country: "India",
  wifiSpeed: "140 Mbps",
  internDuration: "1-6 Months",
  distanceFromTechPark: "600m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Cognizant"],
  internFriendlyRating: 4.4,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "1 km",
  availableFrom: new Date("2026-07-18"),
  recommendedFor: ["IT Interns"]
},

{
  title: "Vadodara Intern Residency",
  description: "Budget-friendly intern PG near IT SEZ Vadodara.",
  image:"https://images.unsplash.com/photo-1557367184-663fba4b8b91?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D",
  price: 6200,
  location: "Vadodara",
  country: "India",
  wifiSpeed: "85 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "1.7 km",
  studyDesk: true,
  powerBackup: false,
  cctv: true,
  biometricEntry: false,
  genderType: "Boys Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["L&T Technology Services"],
  internFriendlyRating: 3.7,
  verifiedByPlatform: false,
  workspaceType: "Common Workspace",
  metroDistance: "2.5 km",
  availableFrom: new Date("2026-06-27"),
  recommendedFor: ["Mechanical Interns"]
},

{
  title: "Thane Corporate Intern Stay",
  description: "Premium intern stay near Wagle Estate IT Park.",
  image:"https://plus.unsplash.com/premium_photo-1678790909398-961ffa85d03d?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fGhvc3RlbHxlbnwwfHwwfHx8MA%3D%3D",
  price: 9800,
  location: "Thane",
  country: "India",
  wifiSpeed: "200 Mbps",
  internDuration: "2-6 Months",
  distanceFromTechPark: "500m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: true,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["TCS", "Accenture"],
  internFriendlyRating: 4.6,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "700m",
  availableFrom: new Date("2026-07-20"),
  recommendedFor: ["Corporate Interns"]
},

{
  title: "Visakhapatnam Tech Habitat",
  description: "Comfortable intern PG near Rushikonda IT SEZ.",
  image : "https://plus.unsplash.com/premium_photo-1679088034974-2c9c01d59992?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8aG9zdGVsfGVufDB8fDB8fHww",
  price: 6700,
  location: "Visakhapatnam",
  country: "India",
  wifiSpeed: "95 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "1 km",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Girls Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Wipro"],
  internFriendlyRating: 4.1,
  verifiedByPlatform: true,
  workspaceType: "Common Workspace",
  metroDistance: "2 km",
  availableFrom: new Date("2026-07-06"),
  recommendedFor: ["IT Interns"]
},

{
  title: "Surat Digital Intern Lodge",
  description: "Affordable and secure intern stay near IT hubs.",
  image : "https://images.unsplash.com/photo-1623625434462-e5e42318ae49?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG9zdGVsfGVufDB8fDB8fHww",
  price: 6300,
  location: "Surat",
  country: "India",
  wifiSpeed: "90 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "1.4 km",
  studyDesk: true,
  powerBackup: false,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["Reliance Industries"],
  internFriendlyRating: 3.9,
  verifiedByPlatform: false,
  workspaceType: "Common Workspace",
  metroDistance: "2.2 km",
  availableFrom: new Date("2026-06-30"),
  recommendedFor: ["Management Interns"]
},

{
  title: "Mysore Tech Park Residency",
  description: "Quiet intern-friendly stay near Hebbal Industrial Area.",
  image : "https://plus.unsplash.com/premium_photo-1716767947952-42e8fe3a28a2?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8aG9zdGVsfGVufDB8fDB8fHww",
  price: 7100,
  location: "Mysore",
  country: "India",
  wifiSpeed: "110 Mbps",
  internDuration: "1-4 Months",
  distanceFromTechPark: "850m",
  studyDesk: true,
  powerBackup: true,
  cctv: true,
  biometricEntry: false,
  genderType: "Co-Living",
  roomType: "Private",
  mealsIncluded: true,
  laundry: true,
  nearCompanies: ["Infosys"],
  internFriendlyRating: 4.2,
  verifiedByPlatform: true,
  workspaceType: "Private Study Room",
  metroDistance: "1.5 km",
  availableFrom: new Date("2026-07-14"),
  recommendedFor: ["Engineering Interns"]
},

{
  title: "Patna Tech Intern Stay",
  description: "Budget intern housing near upcoming IT offices.",
  image:"https://images.unsplash.com/photo-1625249927451-ba4973d5b222?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8Y29kaW5nJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
  price: 5800,
  location: "Patna",
  country: "India",
  wifiSpeed: "75 Mbps",
  internDuration: "1-3 Months",
  distanceFromTechPark: "2 km",
  studyDesk: true,
  powerBackup: false,
  cctv: true,
  biometricEntry: false,
  genderType: "Boys Only",
  roomType: "Shared",
  mealsIncluded: true,
  laundry: false,
  nearCompanies: ["Wipro"],
  internFriendlyRating: 3.6,
  verifiedByPlatform: false,
  workspaceType: "Common Workspace",
  metroDistance: "3 km",
  availableFrom: new Date("2026-06-26"),
  recommendedFor: ["Software Interns"]
}
];

module.exports = { data: sampleListings };
