const sampleListings = [
  {
    title: "Intern Room Near Electronic City",
    description: "Budget-friendly shared room ideal for tech interns. Fast WiFi and walking distance to IT parks.",
    image: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=60",
    price: 8500,
    location: "Bangalore",
    country: "India",
    wifiSpeed: "120 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "1 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["Infosys", "TCS", "Wipro"],
    internFriendlyRating: 4.5,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "900m",
    availableFrom: new Date("2026-06-01"),
    recommendedFor: ["Engineering Interns", "Software Developers"],
  },

  {
    title: "Private Studio for Corporate Interns",
    description: "Fully furnished private studio perfect for MBA and corporate interns.",
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=60",
    price: 16000,
    location: "Gurgaon",
    country: "India",
    wifiSpeed: "300 Mbps",
    internDuration: "1-6 Months",
    distanceFromTechPark: "400m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Co-Living",
    roomType: "Private",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Deloitte", "Google", "Accenture"],
    internFriendlyRating: 4.8,
    verifiedByPlatform: true,
    workspaceType: "Private Study Room",
    metroDistance: "250m",
    availableFrom: new Date("2026-05-15"),
    recommendedFor: ["MBA Students", "Corporate Interns"],
  },

  {
    title: "Girls PG Near Cyber Hub",
    description: "Safe and secure girls-only accommodation with CCTV and biometric entry.",
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Delhi",
    country: "India",
    wifiSpeed: "150 Mbps",
    internDuration: "1-4 Months",
    distanceFromTechPark: "1.5 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Girls Only",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["EY", "HCL", "KPMG"],
    internFriendlyRating: 4.6,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "300m",
    availableFrom: new Date("2026-06-10"),
    recommendedFor: ["Finance Interns", "Female Students"],
  },

  {
    title: "Co-Living Intern House",
    description: "Modern co-living space with networking-friendly environment.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=60",
    price: 10500,
    location: "Hyderabad",
    country: "India",
    wifiSpeed: "200 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "800m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Microsoft", "Amazon"],
    internFriendlyRating: 4.7,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "1 km",
    availableFrom: new Date("2026-05-25"),
    recommendedFor: ["Engineering Interns", "Startup Interns"],
  },

  {
    title: "Affordable Boys Internship PG",
    description: "Budget boys-only PG near major IT offices with high-speed broadband.",
    image: "https://images.unsplash.com/photo-1617098474202-0d0f60a09e1c?auto=format&fit=crop&w=800&q=60",
    price: 7500,
    location: "Kolkata",
    country: "India",
    wifiSpeed: "100 Mbps",
    internDuration: "1-2 Months",
    distanceFromTechPark: "1.3 km",
    studyDesk: true,
    powerBackup: false,
    cctv: true,
    biometricEntry: false,
    genderType: "Boys Only",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: false,
    nearCompanies: ["TCS", "Cognizant"],
    internFriendlyRating: 4.2,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "700m",
    availableFrom: new Date("2026-06-05"),
    recommendedFor: ["Engineering Students"],
  },

  // 15 more simplified but fully valid entries
  {
    title: "Intern Flat Near Hinjewadi IT Park",
    description: "Shared apartment ideal for short-term tech internships.",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=60",
    price: 9000,
    location: "Pune",
    country: "India",
    wifiSpeed: "150 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "600m",
    studyDesk: true,
    powerBackup: true,
    cctv: false,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["Infosys", "Capgemini"],
    internFriendlyRating: 4.4,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "1.2 km",
    availableFrom: new Date("2026-06-20"),
    recommendedFor: ["Software Interns"],
  },

  {
    title: "Luxury Internship Suite",
    description: "Premium private suite for high-level corporate internships.",
    image: "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=800&q=60",
    price: 18000,
    location: "Mumbai",
    country: "India",
    wifiSpeed: "400 Mbps",
    internDuration: "1-6 Months",
    distanceFromTechPark: "300m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: true,
    genderType: "Co-Living",
    roomType: "Private",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["JP Morgan", "BCG"],
    internFriendlyRating: 4.9,
    verifiedByPlatform: true,
    workspaceType: "Private Study Room",
    metroDistance: "200m",
    availableFrom: new Date("2026-05-01"),
    recommendedFor: ["MBA Interns", "Finance Interns"],
  },

  {
    title: "Student Hostel Near Tech Corridor",
    description: "Affordable hostel stay perfect for 2-month internships.",
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=60",
    price: 7000,
    location: "Chennai",
    country: "India",
    wifiSpeed: "80 Mbps",
    internDuration: "1-2 Months",
    distanceFromTechPark: "2 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["Zoho", "Cognizant"],
    internFriendlyRating: 4.1,
    verifiedByPlatform: false,
    workspaceType: "Common Workspace",
    metroDistance: "900m",
    availableFrom: new Date("2026-06-12"),
    recommendedFor: ["First-Time Interns"],
  },

  {
    title: "Noida Intern Co-Living Space",
    description: "Modern co-living setup with fast WiFi and shared workspace.",
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=60",
    price: 9500,
    location: "Noida",
    country: "India",
    wifiSpeed: "200 Mbps",
    internDuration: "1-3 Months",
    distanceFromTechPark: "700m",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: false,
    laundry: true,
    nearCompanies: ["HCL", "Adobe"],
    internFriendlyRating: 4.6,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "500m",
    availableFrom: new Date("2026-06-08"),
    recommendedFor: ["Tech Interns"],
  },

  {
    title: "Ahmedabad Intern Residency",
    description: "Secure and verified accommodation near major IT hubs.",
    image: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=60",
    price: 8200,
    location: "Ahmedabad",
    country: "India",
    wifiSpeed: "120 Mbps",
    internDuration: "1-4 Months",
    distanceFromTechPark: "1 km",
    studyDesk: true,
    powerBackup: true,
    cctv: true,
    biometricEntry: false,
    genderType: "Co-Living",
    roomType: "Shared",
    mealsIncluded: true,
    laundry: true,
    nearCompanies: ["TCS", "Infosys"],
    internFriendlyRating: 4.3,
    verifiedByPlatform: true,
    workspaceType: "Common Workspace",
    metroDistance: "600m",
    availableFrom: new Date("2026-06-18"),
    recommendedFor: ["Engineering Interns"],
  },
];

module.exports = { data: sampleListings };
